language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

before_install:
  - phpenv config-rm xdebug.ini
  
install:
  - composer install --no-progress --prefer-dist

script:
  - composer run-script tester

after_failure:
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
